<?php

require_once('src/GrammaireDeChomsky.php');
require_once('src/Regle.php');

/**
 * Test class for GrammaireDeChomsky.
 * Generated by PHPUnit on 2011-05-02 at 13:03:30.
 */
class GrammaireDeChomskyTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var GrammaireDeChomsky
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GrammaireDeChomsky;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testAjoute().
     */
    public function testAjoute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAntecedentsDe().
     */
    public function testAntecedentsDe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        $r[] = new Regle("A", "B", "C");
        $g = new GrammaireDeChomsky( $r );
        $this->assertEquals( "$g", "A -> B C" );

        $r[] = new Regle("X", "Y", "Z");
        $g = new GrammaireDeChomsky( $r );
        $this->assertEquals( "$g", "A -> B C\nX -> Y Z" );
    }
}
?>
