<?php

require_once('src/Regle.php');

/**
 * Test class for Regle.
 * Generated by PHPUnit on 2011-05-02 at 12:38:25.
 */
class RegleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Regle
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Regle("A","B","C");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testDonne().
     */
    public function testDonne()
    {
        $r = $this->object;

        $this->assertFalse( $r->donne("") );
        $this->assertFalse( $r->donne("A") );

        $this->assertTrue(  $r->donne("B") );
        $this->assertTrue(  $r->donne("C") );
        $this->assertTrue(  $r->donne("C","B") );
        $this->assertTrue(  $r->donne("B","C") );
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        $r = $this->object;

        $this->assertEquals( "$r", "A -> B C" );
    }
}
?>
