language: php
php:
  - 5.3
  - 5.4
  - 5.5

install:
  - composer install --dev --prefer-dist

script:
  - ./vendor/bin/phpcs --warning-severity=0 --standard=PSR2 src tests
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - ./vendor/bin/phpcpd src/ tests/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
