language: php
php:
  - 5.3

before_script:
  - composer install --dev --prefer-dist

script:
  - ./vendor/bin/phpcs --warning-severity=0 --standard=PSR2 src test
  - ./vendor/bin/phpunit --coverage-text
