<?php
/**
 * Test class for RewriteRule.
 * Generated by PHPUnit on 2011-05-07 at 23:59:05.
 */
class RewriteRuleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var RewriteRule
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RewriteRule;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
